filterpackage/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='Index')
]

movies/models.py
from django.db import models


class Movie(models.Model):

    GENRE_CHOICES = (
        ('action', '動作片'),
        ('romance', '愛情片'),
        ('drama', '劇情片'),
    )

    title = models.CharField(max_length=100)  # 電影名稱
    genre = models.CharField(max_length=20, choices=GENRE_CHOICES)  # 電影類型
    release_year = models.IntegerField()  # 年份

movies/views.py
from django.shortcuts import render
from .models import Movie
from .filters import MovieFilter


def index(request):
    movies = Movie.objects.all()

    movieFilter = MovieFilter(queryset=movies)

    if request.method == "POST":
        movieFilter = MovieFilter(request.POST, queryset=movies)

    context = {
        'movieFilter': movieFilter
    }

    return render(request, 'movies/index.html', context)

movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}

<form method='POST'>
    {% csrf_token %}
    名稱：{{ movieFilter.form.title }}
    類型：{{ movieFilter.form.genre }}
    年份：{{ movieFilter.form.release_year }}
    <input type="submit" class="btn btn-primary" value="查詢" />
</form>
<br />
<table class="table">
    <thead>
        <th>名稱</th>
        <th>類型</th>
        <th>年份</th>
    </thead>
    <tbody>
        {% for movie in movieFilter.qs %}
        <tr>
            <td>{{ movie.title }}</td>
            <td>{{ movie.get_genre_display }}</td>
            <td>{{ movie.release_year }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock  %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>Movie</title>
  </head>
  <body>
    <div class="container">
        <h1>Movie Search</h1>
        <br />
        {% block content %}
        {% endblock  %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>